export const Employees = [
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },
  {
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },{
    id: 98878,
    employee_code: 26792,
    employee_name: 'دينا مصطفى محمد داود',
    branch_code: null,
    branch_name: null,
    sector_name: 'البنك الرئيسي',
    sector_code: 990000000,
  },

];
